namespace ProjectLogic;
//All the objects in the game
public enum Object
{
  none,
  MacheteCurvo,
  Revolver,
  MacheteLargo,
  MacheteCorto,
  MacheteSinFilo,
  Fusiles,
  Granadas,
  CasacaAzul,
  CamisaBlanca,
  RopaGastada,
  TrajeNegro,
  CasacaAzulCondecorada,
  EspadadaCruzado,
  Daga,
  Maza,
  ArcoLargo,
  Ballesta,
  CapaSombria,
  ArmaduraCuero,
  CuchilloEnvenenado,
  ArmaduraVerdadera,
  ArmaduraPesada,
  ArmaduraOscura,
  LlaveLaberinto,
  CruzSagrada,
  CotaDeMallas,
  Colt1911,
  GabardinaNegra,
  Magnum,
  Thopsom,
  Escopeta,
  Lupara,
  Bate,
  Martillo,
  Paraguas,
  Vara,
  Palo,
  Manopla,
  Chaleco,
  CamisaDeLaSuerte,
  TrajeElegante,
  ArmaduraTintada,
  Capucha,
  ArmaduraDiamante,
  ArmaduraOro,
  RopaCampaña,
  CascoCruzado,
  ArmaduraDeFlores,
  TrajePielDeIndio,
  Lanza,
  MangoPodrido,
  ArmaduraPuntiaguda,
}
public class ObjectsStats
{
//Stats,weight and descriptions of all the objects in dictionarys
  public static Dictionary<Object, int> StatsForce = new Dictionary<Object, int>()
    {
    {Object.none,0},
    {Object.Fusiles,3},
    {Object.MacheteCurvo,3},
    {Object.Revolver,3},
    {Object.MacheteLargo,4},
    {Object.MacheteCorto,3},
    {Object.MacheteSinFilo,2},
    {Object.Granadas,4},
    {Object.CasacaAzul,0},
    {Object.CamisaBlanca,0},
    {Object.RopaGastada,0},
    {Object.TrajeNegro,0},
    {Object.CasacaAzulCondecorada,0},
    {Object.EspadadaCruzado,10},
    {Object.Daga,6},
    {Object.Maza,8},
    {Object.ArcoLargo,9},
    {Object.Ballesta,10},
    {Object.CapaSombria,0},
    {Object.ArmaduraCuero,0},
    {Object.CuchilloEnvenenado,12},
    {Object.ArmaduraVerdadera,0},
    {Object.ArmaduraPesada,0},
    {Object.ArmaduraOscura,0},
    {Object.LlaveLaberinto,0},
    {Object.CruzSagrada,8},
    {Object.CotaDeMallas,0},
    {Object.Colt1911,5},
    {Object.GabardinaNegra,0},
    {Object.Magnum,6},
    {Object.Thopsom,12},
    {Object.Escopeta,11},
    {Object.Lupara,10},
    {Object.Bate,6},
    {Object.Martillo,5},
    {Object.Paraguas,3},
    {Object.Vara,4},
    {Object.Palo,6},
    {Object.Manopla,4},
    {Object.Chaleco,0},
    {Object.CamisaDeLaSuerte,0},
    {Object.TrajeElegante,0},
    {Object.ArmaduraTintada,0},
    {Object.Capucha,0},
    {Object.ArmaduraDiamante,0},
    {Object.ArmaduraOro,0},
    {Object.RopaCampaña,0},
    {Object.CascoCruzado,0},
    {Object.ArmaduraDeFlores,0},
    {Object.TrajePielDeIndio,0},
    {Object.Lanza,7},
    {Object.MangoPodrido,15},
    {Object.ArmaduraPuntiaguda,0},
    };
  public static Dictionary<Object, int> StatsArmor = new Dictionary<Object, int>()
    {
    {Object.none,0},
    {Object.Fusiles,0},
    {Object.MacheteCurvo,0},
    {Object.Revolver,0},
    {Object.MacheteLargo,0},
    {Object.MacheteCorto,0},
    {Object.MacheteSinFilo,0},
    {Object.Granadas,0},
    {Object.CasacaAzul,4},
    {Object.CamisaBlanca,2},
    {Object.RopaGastada,1},
    {Object.TrajeNegro,3},
    {Object.CasacaAzulCondecorada,5},
    {Object.EspadadaCruzado,0},
    {Object.Daga,0},
    {Object.Maza,0},
    {Object.ArcoLargo,0},
    {Object.Ballesta,0},
    {Object.CapaSombria,9},
    {Object.ArmaduraCuero,5},
    {Object.CuchilloEnvenenado,0},
    {Object.ArmaduraVerdadera,10},
    {Object.ArmaduraPesada,15},
    {Object.ArmaduraOscura,13},
    {Object.LlaveLaberinto,0},
    {Object.CruzSagrada,0},
    {Object.CotaDeMallas,8},
    {Object.Colt1911,0},
    {Object.GabardinaNegra,6},
    {Object.Magnum,0},
    {Object.Thopsom,0},
    {Object.Escopeta,0},
    {Object.Lupara,0},
    {Object.Bate,0},
    {Object.Martillo,0},
    {Object.Paraguas,0},
    {Object.Vara,0},
    {Object.Palo,0},
    {Object.Manopla,0},
    {Object.Chaleco,10},
    {Object.CamisaDeLaSuerte,7},
    {Object.TrajeElegante,8},
    {Object.ArmaduraTintada,11},
    {Object.Capucha,6},
    {Object.ArmaduraDiamante,17},
    {Object.ArmaduraOro,12},
    {Object.RopaCampaña,7},
    {Object.CascoCruzado,10},
    {Object.ArmaduraDeFlores,1},
    {Object.TrajePielDeIndio,5},
    {Object.Lanza,0},
    {Object.MangoPodrido,0},
    {Object.ArmaduraPuntiaguda,11},
    };
  public static Dictionary<Object, int> StatsWeight = new Dictionary<Object, int>()
    {
    {Object.none,0},
    {Object.Fusiles,30},
    {Object.MacheteCurvo,25},
    {Object.Revolver,10},
    {Object.MacheteLargo,27},
    {Object.MacheteCorto,20},
    {Object.MacheteSinFilo,19},
    {Object.Granadas,11},
    {Object.CasacaAzul,12},
    {Object.CamisaBlanca,10},
    {Object.RopaGastada,5},
    {Object.TrajeNegro,17},
    {Object.CasacaAzulCondecorada,15},
    {Object.EspadadaCruzado,50},
    {Object.Daga,20},
    {Object.Maza,70},
    {Object.ArcoLargo,45},
    {Object.Ballesta,56},
    {Object.CapaSombria,20},
    {Object.ArmaduraCuero,33},
    {Object.CuchilloEnvenenado,20},
    {Object.ArmaduraVerdadera,70},
    {Object.ArmaduraPesada,90},
    {Object.ArmaduraOscura,75},
    {Object.LlaveLaberinto,2},
    {Object.CruzSagrada,23},
    {Object.CotaDeMallas,43},
    {Object.Colt1911,15},
    {Object.GabardinaNegra,25},
    {Object.Magnum,17},
    {Object.Thopsom,57},
    {Object.Escopeta,60},
    {Object.Lupara,34},
    {Object.Bate,36},
    {Object.Martillo,19},
    {Object.Paraguas,17},
    {Object.Vara,19},
    {Object.Palo,15},
    {Object.Manopla,6},
    {Object.Chaleco,46},
    {Object.CamisaDeLaSuerte,15},
    {Object.TrajeElegante,34},
    {Object.ArmaduraTintada,69},
    {Object.Capucha,23},
    {Object.ArmaduraDiamante,150},
    {Object.ArmaduraOro,130},
    {Object.RopaCampaña,35},
    {Object.CascoCruzado,59},
    {Object.ArmaduraDeFlores,12},
    {Object.TrajePielDeIndio,29},
    {Object.Lanza,39},
    {Object.MangoPodrido,10},
    {Object.ArmaduraPuntiaguda,70},
    };
  public static Dictionary<Object, string> DescriptionObject = new Dictionary<Object, string>()
  {
    {Object.Fusiles,"Un fusil utilizado en la guerra de 1898 ,depende de la humedad del aire para que la pólvora funcione"},
    {Object.MacheteCurvo,"Un machete con trayectoria curva idonio para cortar caña pero es usado para cortar carne"},
    {Object.Revolver,"Un lindo modelo antiguo (la verdad es que no se si es un revolver)"},
    {Object.MacheteLargo,"Machete de gran longitud idonio para la caballería"},
    {Object.MacheteCorto,"Machete corto (el único que había)"},
    {Object.MacheteSinFilo,"Machete de esclavo sin filo de tanto usarse"},
    {Object.Granadas,"Granadas  peligrosas , su paquete dice CUIDADO NO EXPLOTES!"},
    {Object.CasacaAzul,"Un uniforme utilizado por los españoles en la epoca moderna"},
    {Object.CamisaBlanca,"Camisa típica cubana con buena limpieza ,aunque no va a durar mucho"},
    {Object.RopaGastada,"Ropa sin lavar desde el Zanjón"},
    {Object.TrajeNegro,"Típico traje de la intelectualidad cubana ,corbata y todo"},
    {Object.CasacaAzulCondecorada,"Traje de generales españoles con estrellas del valor"},
    {Object.EspadadaCruzado,"Espada en forma de cruz ,que hermosa se ve contra la luz de la lampara"},
    {Object.Daga,"Una daga pequeña"},
    {Object.Maza,"Es una maza muy pesada, puede que no valga la pena"},
    {Object.ArcoLargo,"Un arco utilizado por los ingleses en los tiempos de la guerra de los 100 años"},
    {Object.Ballesta,"Ballesta francesa ,se sabe por la marca"},
    {Object.CapaSombria,"Una capa bastante tenebrosa si me preguntas"},
    {Object.ArmaduraCuero,"Armadura típica para empezar un juego"},
    {Object.CuchilloEnvenenado,"Chuchilla mortal ,aunque en este juego no muere nadie"},
    {Object.ArmaduraVerdadera,"Armadura de caballero bien cuidada"},
    {Object.ArmaduraPesada,"Armadura muy pesada de acero"},
    {Object.ArmaduraOscura,"Armadura adornada con una cruz inversa de color negro"},
    {Object.LlaveLaberinto,"Llave de salida para el laberinto"},
    {Object.CruzSagrada,"Cruz que aleja todos los males (es una daga envenenada oculta)"},
    {Object.CotaDeMallas,"Protección estandar de la edad media"},
    {Object.Colt1911,"El modelo de arma favorita del creador por lo que está más rota de lo que debería"},
    {Object.GabardinaNegra,"Gabardina que viene a combo con un sombrero que pensarías que no te protegerá pero si lo hace"},
    {Object.Magnum,"Una magnum muy hermosa y  que si la disparas lo mas probable es que todos te oigan"},
    {Object.Thopsom,"Es la única arma de disparo repetido del  juego por lo que está absurdamente rota"},
    {Object.Escopeta,"Una escopeta bastante buena en la ofensiva y defensiva"},
    {Object.Lupara,"Una lupara que te servirá para eliminar a tus enemigos con estilo"},
    {Object.Bate,"Un bate de baseball firmado por alguien"},
    {Object.Martillo,"Un martillo liviano manchado de sangre por alguna razón"},
    {Object.Paraguas,"Un paraguas bastante inutil"},
    {Object.Vara,"Una vara de monje budista"},
    {Object.Palo,"Un simple palo"},
    {Object.Manopla,"Una manopla de hierro"},
    {Object.Chaleco,"Un chaleco antibalas resistente y de color negro"},
    {Object.CamisaDeLaSuerte,"LA camisa que si te pones de seguro tienes suerte y llegas al final rápido"},
    {Object.TrajeElegante,"Un traje de fiestas bastante caro como para estropiarlo en el laberinto"},
    {Object.ArmaduraTintada,"Una armadura con diferentes colores"},
    {Object.Capucha,"Un traje con capucha que me recuerda a algo"},
    {Object.ArmaduraDiamante,"Armadura que posiblemente te llevará la mitad del inventario pero vale la pena porque es de diamante"},
    {Object.ArmaduraOro,"Una armadura con mucho valor monetario"},
    {Object.RopaCampaña,"Ropa de soldado norteamericano en el siglo XIX"},
    {Object.CascoCruzado,"Casco con la cruz sagrada"},
    {Object.ArmaduraDeFlores,"Armadura bastante afeminada"},
    {Object.TrajePielDeIndio,"Traje hecho con hmm...no voy a continuar"},
    {Object.Lanza,"Lanza de cobre con un diseño oriental"},
    {Object.MangoPodrido,"El arma más poderosa del juego ,lo más probable es que sea una muerte rápida para tu enemigo"},
    {Object.ArmaduraPuntiaguda,"Una armaduara defensiva modelo,aunque te da comesón"},
  };
}